### ISSUE TITLE
`Nat.Pow` is no longer in Mathlib4

### ISSUE THREAD

**Issue by rwst** [mo271/formal_book#49]
Trying chapter 1:
```
stderr:
error: 'Mathlib.Data.Nat.Pow': no such file or directory (error code: 2)
  file: ./.lake/packages/mathlib/././Mathlib/Data/Nat/Pow.lean
```
It appears `Nat.Pow` is no longer in Mathlib4.

**Comment by mo271** [comment]
Thanks for trying this. I will do a rebase with up-to-date Mathlib soon.

**Comment by mo271** [comment]
bump complete: https://github.com/mo271/formal_book/commit/d3dc53e36cca085106c592e04d7dddb7db638fa0
Should now be in sync with current Mathlib
